# Generated by Django 5.2.3 on 2025-06-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_telegram_id_telegramuser_chat_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegramuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
