# Generated by Django 5.2.3 on 2025-06-20 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_telegramuser_first_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegramuser",
            old_name="username",
            new_name="last_name",
        ),
        migrations.RenameField(
            model_name="telegramuser",
            old_name="chat_id",
            new_name="telegram_id",
        ),
    ]
