# Generated by Django 5.2.3 on 2025-06-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_rename_username_telegramuser_last_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
